language: csharp
sudo: required
mono: none
dist: xenial
dotnet: 3.0
os:
  - linux
  - osx

script:
  - dotnet restore
  - dotnet build -c Release --no-restore --framework netstandard2 ./src
  - dotnet test  -c Release --no-restore --framework netcoreapp2.1 ./test