version: 0.2.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: j4sELCwhVRRjNXFVhjPZjdG4y2itz8jrExhlyDU/lTiLlRQ/P4brB69MGQRFBQae
install:
  - choco install gitversion.portable -pre -y
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: false
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  project: IpfsCore.sln
  publish_nuget: false
  verbosity: minimal

after_build:
  - cmd: nuget pack src\IpfsCore.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Ipfs.Core.%GitVersion_NuGetVersion%.nupkg"

after_test: 
# Generate coverage report
    - set
    - packages\OpenCover.4.6.210-rc\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:test//bin/Release/Ipfs.Core.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover coverage.xml

# publish NuGet package on tag build
deploy:
- provider: NuGet
  api_key:
    secure: OdmGEj/l0K0ZPDmXAYx+fryCzV012eTrM29ALBuL0waxvwLvrufdDXiI+1iNhWEG
  on:
    appveyor_repo_tag: true
