version: 0.2.0.{build}
install:
  - choco install gitversion.portable -pre -y
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: false
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release
build:
  publish_nuget: false
  verbosity: minimal

after_build:
  - cmd: nuget pack src\IpfsCore.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Ipfs.Core.%GitVersion_NuGetVersion%.nupkg"

# publish NuGet package on tag build
deploy:
- provider: NuGet
  api_key:
    secure: OdmGEj/l0K0ZPDmXAYx+fryCzV012eTrM29ALBuL0waxvwLvrufdDXiI+1iNhWEG
  on:
    appveyor_repo_tag: true
