version: 0.2.0.{build}
install:
  - choco install gitversion.portable -pre -y
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{GitVersion_NuGetVersion}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
  - cmd: nuget restore
  - ps: gitversion /l console /output buildserver
  - cmd: echo "%GitVersion_NuGetVersion%"
build:
  publish_nuget: true
  verbosity: minimal
