version: 0.2.0.{build}
install:
  - choco install gitversion.portable -pre -y
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: false
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - cmd: echo "%GitVersion_NuGetVersion%"
build:
  publish_nuget: false
  verbosity: minimal

after_build:
  - cmd: ECHO nuget pack src\IpfsCore.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack src\IpfsCore.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "src.%GitVersion_NuGetVersion%.nupkg"
